name: demoserreautonome

services:
  app:
    build: .
    image: serre-app:ci
    container_name: serre-app
    healthcheck:
      # CMD-SHELL évite certains soucis de parsing sous Windows
      test: ["CMD-SHELL", "curl -fs http://localhost:5000/api/latest || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  robot:
    image: ppodgorsek/robot-framework:latest
    container_name: serre-tests
    depends_on:
      app:
        condition: service_healthy
    environment:
      BROWSER: chrome
      TZ: Europe/Paris
    volumes:
      # Tests en lecture seule et rapports persistés pour Jenkins
      - ./tests:/opt/robotframework/tests:ro
      - ./reports:/opt/robotframework/reports
    # IMPORTANT :
    #  - chemin ABSOLU des tests (dans le conteneur)
    #  - injection d'une variable Robot SELENIUM_OPTIONS contenant les flags Chrome
    command:
      - robot
      - -d
      - /opt/robotframework/reports
      - --xunit
      - /opt/robotframework/reports/xunit.xml
      - -v
      - BASE_URL:http://app:5000
      - -v
      - SELENIUM_OPTIONS:--no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-profile
      - /opt/robotframework/tests
    restart: "no"
