name: demoserreautonome

services:
  app:
    build: .
    image: serre-app:ci
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/healthz"]
      interval: 5s
      timeout: 2s
      retries: 20
      start_period: 10s

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2g

  robot:
    image: ppodgorsek/robot-framework:latest
    depends_on:
      app:
        condition: service_healthy
      chrome:
        condition: service_started
    environment:
      ROBOT_TESTS_DIR: /opt/robotframework/tests
      ROBOT_REPORTS_DIR: /opt/robotframework/reports
      SELENIUM_HOST: chrome
      SELENIUM_PORT: 4444
    volumes:
      - ./tests:/opt/robotframework/tests:ro
      - ./reports:/opt/robotframework/reports
    command: >
      robot
      -d /opt/robotframework/reports
      --xunit /opt/robotframework/reports/xunit.xml
      -v BASE_URL:http://app:5000
      tests
