version: "3.8"
services:
  app:
    build: .
    image: serre-app:ci
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:5000/api/latest"]
      interval: 10s
      timeout: 3s
      retries: 10

  robot:
    image: ppodgorsek/robot-framework:latest
    depends_on:
      app:
        condition: service_healthy
    environment:
      BROWSER: chrome
    volumes:
      - ./tests:/opt/robotframework/tests:ro
      - ./reports:/opt/robotframework/reports
    command: >
      -d /opt/robotframework/reports
      -v BASE_URL:http://app:5000
      tests
