name: demoserreautonome

services:
  app:
    build: .
    image: serre-app:ci
    container_name: serre-app
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:5000/api/latest"]
      interval: 10s
      timeout: 3s
      retries: 10

  robot:
    image: ppodgorsek/robot-framework:latest
    container_name: serre-tests
    depends_on:
      app:
        condition: service_healthy
    environment:
      BROWSER: chrome
    volumes:
      # Tes tests côté host -> dans le conteneur à l’emplacement attendu par l’image
      - ./tests:/opt/robotframework/tests:ro
      # Répertoire de rapports
      - ./reports:/opt/robotframework/reports
    # IMPORTANT : utiliser un chemin ABSOLU pour la suite de tests
    command: [
      "robot",
      "-d", "/opt/robotframework/reports",
      "--xunit", "/opt/robotframework/reports/xunit.xml",
      "-v", "BASE_URL:http://app:5000",
      "/opt/robotframework/tests"           # <— au lieu de "tests"
    ]
    restart: "no"
