name: demoserreautonome

services:
  app:
    build: .
    image: serre-app:ci
    container_name: serre-app
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:5000/api/latest || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  chrome:
    image: selenium/standalone-chrome:latest   
    container_name: chrome
    shm_size: 2g
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:4444/status | grep -q ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  robot:
    image: ppodgorsek/robot-framework:latest
    container_name: serre-tests
    depends_on:
      app:
        condition: service_healthy
      chrome:
        condition: service_healthy
    environment:
      BROWSER: chrome
      BASE_URL: http://app:5000
      REMOTE_URL: http://chrome:4444/wd/hub
    volumes:
      - ./tests:/opt/robotframework/tests:ro
      - ./reports:/opt/robotframework/reports
    command:
      - robot
      - -d
      - /opt/robotframework/reports
      - --xunit
      - /opt/robotframework/reports/xunit.xml
      - /opt/robotframework/tests
